/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicClassificarRouteImport } from './routes/api/public/classificar'
import { Route as ApiPublicCompararRouteImport } from './routes/api/public/comparar'
import { Route as ApiPublicGerarTextoRouteImport } from './routes/api/public/gerar-texto'
import { Route as ApiPublicRecomendarRouteImport } from './routes/api/public/recomendar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClassificarRoute = ApiPublicClassificarRouteImport.update({
  id: '/api/public/classificar',
  path: '/api/public/classificar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCompararRoute = ApiPublicCompararRouteImport.update({
  id: '/api/public/comparar',
  path: '/api/public/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGerarTextoRoute = ApiPublicGerarTextoRouteImport.update({
  id: '/api/public/gerar-texto',
  path: '/api/public/gerar-texto',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRecomendarRoute = ApiPublicRecomendarRouteImport.update({
  id: '/api/public/recomendar',
  path: '/api/public/recomendar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/classificar': typeof ApiPublicClassificarRoute
  '/api/public/comparar': typeof ApiPublicCompararRoute
  '/api/public/gerar-texto': typeof ApiPublicGerarTextoRoute
  '/api/public/recomendar': typeof ApiPublicRecomendarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/classificar': typeof ApiPublicClassificarRoute
  '/api/public/comparar': typeof ApiPublicCompararRoute
  '/api/public/gerar-texto': typeof ApiPublicGerarTextoRoute
  '/api/public/recomendar': typeof ApiPublicRecomendarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/classificar': typeof ApiPublicClassificarRoute
  '/api/public/comparar': typeof ApiPublicCompararRoute
  '/api/public/gerar-texto': typeof ApiPublicGerarTextoRoute
  '/api/public/recomendar': typeof ApiPublicRecomendarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/classificar'
    | '/api/public/comparar'
    | '/api/public/gerar-texto'
    | '/api/public/recomendar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/classificar'
    | '/api/public/comparar'
    | '/api/public/gerar-texto'
    | '/api/public/recomendar'
  id:
    | '__root__'
    | '/'
    | '/api/public/classificar'
    | '/api/public/comparar'
    | '/api/public/gerar-texto'
    | '/api/public/recomendar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicClassificarRoute: typeof ApiPublicClassificarRoute
  ApiPublicCompararRoute: typeof ApiPublicCompararRoute
  ApiPublicGerarTextoRoute: typeof ApiPublicGerarTextoRoute
  ApiPublicRecomendarRoute: typeof ApiPublicRecomendarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/classificar': {
      id: '/api/public/classificar'
      path: '/api/public/classificar'
      fullPath: '/api/public/classificar'
      preLoaderRoute: typeof ApiPublicClassificarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/comparar': {
      id: '/api/public/comparar'
      path: '/api/public/comparar'
      fullPath: '/api/public/comparar'
      preLoaderRoute: typeof ApiPublicCompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gerar-texto': {
      id: '/api/public/gerar-texto'
      path: '/api/public/gerar-texto'
      fullPath: '/api/public/gerar-texto'
      preLoaderRoute: typeof ApiPublicGerarTextoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/recomendar': {
      id: '/api/public/recomendar'
      path: '/api/public/recomendar'
      fullPath: '/api/public/recomendar'
      preLoaderRoute: typeof ApiPublicRecomendarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicClassificarRoute: ApiPublicClassificarRoute,
  ApiPublicCompararRoute: ApiPublicCompararRoute,
  ApiPublicGerarTextoRoute: ApiPublicGerarTextoRoute,
  ApiPublicRecomendarRoute: ApiPublicRecomendarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
